data:
  co.com.invima.procedureonline.echovalue: teestvalue1
  SQL_URL: 'jdbc:sqlserver://192.168.1.23:11433;database=maestra'
  SQL_USERNAME: Invima
  SQL_PASSWORD: Admin2021
  SQL_SCHEMA: dbo
metadata:
  name: srvfirmarotulada
